defmodule JidoMurmur.AgentProfile do
  @moduledoc """
  Behaviour for agent profile modules.

  Provides compile-time validation that profile modules implement
  all required callbacks. Add `@behaviour JidoMurmur.AgentProfile`
  to profile modules to enable compiler warnings for missing callbacks.

  The callbacks `name/0`, `description/0`, `plugins/0`, and `actions/0`
  are generated by `use Jido.AI.Agent`. Adding this behaviour simply
  enables compile-time enforcement that these functions exist.
  """

  @callback name() :: String.t()
  @callback description() :: String.t() | nil
  @callback plugins() :: [module()]
  @callback actions() :: [module()]
end
